### PR TITLE
Rollback new patching

### PR DESCRIPTION
**Pull request by matthewalbani**
@wkj  this rollbacks the new patching but keeps the base commit being added to patch upload args

### CODE REVIEW

**Comment by wkj** [comment]
@matthewalbani should reverted commit be put in a separate branch/PR for now?

**Comment by matthewalbani** [comment]
the revert, reverts the addition of the base commit to patch upload, so i added it as a seperate commit.

**Comment by wkj** [comment]
OK.  I'm setting the version back to 1.30.4.  Once it passes tests should I release it?

**Comment by matthewalbani** [comment]
whoops yea should be 1.30.4 yeah once it passes it can go out

**Pull request merged**
