### PR TITLE
Gem improvments

### PR DESCRIPTION
**Pull request by matthewalbani**
adds references to doc page added in https://github.com/solanolabs/docs/pull/133

also prompts the user to create a snapshot if it fails to create patch instead of failing.

### CODE REVIEW

**Comment by matthewalbani** [comment]
switches the patch creation model to be more reliable.

**Comment by matthewalbani** [comment]
@IsaacChapman when you get a chance will you PTAL

**Comment by IsaacChapman** [comment]
Very nitpicky, but `ANSERER_NOT_Y`?

**Comment by matthewalbani** [comment]
all the cool kids spell it like that

**Comment by IsaacChapman** [comment]
LGTM.

**Comment by matthewalbani** [comment]
i have tried the following with local git of git version 2.7.0
- no snapshot
- snapshot
- snapshot that is ahead of local commit
- snapshot that is behind local commit
- branch that only exists locally
- a local copy with master behind upstream/snapshot commit and a local commit based on local master on a new branch and with a new commit

any thoughts on other things that should be tested?

**Comment by IsaacChapman** [comment]
Not really a scenario for handling with grace, but I'm sure some customer will force push the snapshot's HEAD out of existence in their local branch sooner or later.

**Comment by matthewalbani** [comment]
if it can not find the snapshot commit either locally or upstream it offers to create a new repo snapshot based on local master

**Pull request merged**
