### PR TITLE
CICLI-96

### PR DESCRIPTION
**Pull request by malinovskymax**
Ask for specific account when running solano status in branch shared between multiple orgs.

### CODE REVIEW

**Comment by bkendzior** [comment]
Can we also allow the use of the ```--org``` flag when running ```solano status``` ?

**Comment by malinovskymax** [comment]
@bkendzior I added an `--org` option.

**Comment by bkendzior** [comment]
Could you take a look at test failures?

**Comment by malinovskymax** [comment]
@bkendzior my changes are not related to those failings, they appeared in master branch in some moment in past month, before I started this branch.

**Comment by wkj** [comment]
See https://github.com/solanolabs/solano/pull/73

**Comment by malinovskymax** [comment]
Rebased.

**Comment by wkj** [comment]
Merged

**Pull request closed without merging**
